# Homework 12

*Enter your name and EID here*

**This homework is due on Dec 10, 2019 at 11:59pm. Please submit as a PDF file on Canvas. Before submission, please re-run all cells by clicking "Kernel" and selecting "Restart & Run All."**


**Problem 1 (5 points):** In bioinformatics, k-mers refer to all the possible subsequences (of length k) from a read obtained through DNA sequencing. For example, if the DNA sequencing read is "ATCATCATG", then a the 3-mers in that read include "ATC" (which occurs twice), "TCA" (which occurs twice), "CAT" (occurs twice), and "ATG" (occurs once). You can read more about k-mers on [Wikipedia](https://en.wikipedia.org/wiki/K-mer).

Write a function that takes a string of nucleotides as input and returns a **dictionary** with all 3-mers present in that string, and the number of times that each 3-mer occurs. Then use your function to find the 3-mers in the DNA sequence `my_seq1` defined below.

The output of your function should be a dictionary that is structured like this (although it will have several more entries)

`{"CAG": 2, "AGC": 1, "GCC": 3}`

where each key is a 3-mer itself (e.g., "ATC") and each value is the number of times that 3-mer occurs.



In [1]:
#this chunk lets you have multiple outputs from a single chunk; run it first!
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
# Find all 3-mers in these two sequences
my_seq1 = "ATCATCATG"
my_seq2 = "CAGCCCAATCAGGCTCTACTGCCACTAAACTTACGCAGGATATATTTACGCCGACGTACT"

def findmers(seq,k):
    count = {}
    kmers = len(seq) - k + 1
    for i in range(kmers):
        kmer = seq[i:i+k]
        if kmer not in count:
            count[kmer] = 0
        count[kmer] += 1
    return count

print("my_seq1")
findmers(my_seq1,3)


my_seq1


{'ATC': 2, 'TCA': 2, 'CAT': 2, 'ATG': 1}

In [3]:
findmers(my_seq2,3)

{'CAG': 3,
 'AGC': 1,
 'GCC': 3,
 'CCC': 1,
 'CCA': 2,
 'CAA': 1,
 'AAT': 1,
 'ATC': 1,
 'TCA': 1,
 'AGG': 2,
 'GGC': 1,
 'GCT': 1,
 'CTC': 1,
 'TCT': 1,
 'CTA': 2,
 'TAC': 4,
 'ACT': 4,
 'CTG': 1,
 'TGC': 1,
 'CAC': 1,
 'TAA': 1,
 'AAA': 1,
 'AAC': 1,
 'CTT': 1,
 'TTA': 2,
 'ACG': 3,
 'CGC': 2,
 'GCA': 1,
 'GGA': 1,
 'GAT': 1,
 'ATA': 2,
 'TAT': 2,
 'ATT': 1,
 'TTT': 1,
 'CCG': 1,
 'CGA': 1,
 'GAC': 1,
 'CGT': 1,
 'GTA': 1}

**Problem 2a (3 points):** DNA sequences are typically stored in a format called FASTA (pronounced fast-ay). A single FASTA file may contain many different sequences. For example, you may have a FASTA file for a mouse, and each mouse gene sequence is stored as a separate sequence in that FASTA file. All sequences in a FASTA file begin on a new line with a greater-than symbol "`>`" (without quotes). 

Write a function that takes the *name* of a FASTA file as input, opens that file, counts the number of sequences in the file (by counting the number of lines in the file that start with a “>” symbol), and returns the count. Download the file "[ls_orchid.fasta](https://raw.githubusercontent.com/biopython/biopython/master/Doc/examples/ls_orchid.fasta)" to your computer (should also be on Canvas and on the servers), upload it to your home directory, and use your function to count the number of sequences in the file (by determining the number of greater-than symbols. The file `ls_orchid.fasta` contains nucleotide database results for lady slipper orchids. Test your function on that! Now use the function on the file `CD4.fasta` (on Canvas and on the servers). This file contains amino acid sequences of the CD4 membrane protein that is found on the surface of the immune cells.

How many sequences does each fasta file contain?

In [4]:
#The following code opens the file, reads it into contents, and closes the file

file_handle = open("ls_orchid.fasta", "r") # open in 'r' mode  to read the file
contents = file_handle.read() # reads the entire file 
file_handle.close() # always close at the end

def openAndCount(fasta):
    count = 0
    
    file_handle = open(fasta, "r") # open in 'r' mode  to read the file
    contents = file_handle.read() # reads the entire file 
     # always close at the end
    
    for line in contents:
        if line[0] == ">":
            count += 1
    return count
    file_handle.close()
print(openAndCount("ls_orchid.fasta"))

94


In [5]:
print("number of dequences in CD4.fasta")
print(openAndCount("CD4.fasta"))

number of dequences in CD4.fasta
18


**Problem 2b (2 points):** Often, you will use the biopython package to parse sequences (it makes it much easier)! Take a look at the following code and make sure the number of sequences it returns matches what your function found above (it is returning some extra stuff too). Modify it to give the same output for the CD4.fasta file and to print out the first 30 elements of each sequence.

In [6]:
#!pip3 install biopython # or conda install biopython #if you are not on the servers

from Bio import SeqIO

nseqs=0
for seq_record in SeqIO.parse("ls_orchid.fasta", "fasta"):
    nseqs+=1
    print("sequence",nseqs,"is",len(seq_record),\
          "long, and the first 5 elements are",seq_record.seq[:5] )
print("the number of sequences is", nseqs)

# Modify
print()
print("CD4")
nseqs=0
for seq_record in SeqIO.parse("CD4.fasta", "fasta"):
    nseqs+=1
    print("sequence",nseqs,"is",len(seq_record),\
          "long, and the first 30 elements are",seq_record.seq[:30] )
print("the number of sequences is", nseqs)

ModuleNotFoundError: No module named 'Bio'

**Problem 3 (5 points):** Using **Needleman-Wunsch**, align the following two sequences by hand:

```
CCAGT
ACAAGT
```

Draw out a score matrix, **with the back-tracing arrows**, using the following scoring function:

```
Match: +2
Mismatch: -1
Gap: -1
```

After you have filled out your score matrix, be sure to **write out the final alignment**.

Take a picture of your handwork, upload it to the home directory on the server (or whatever directory you have this assignment in), and replacing `image_name.png` with the actual file name and extension, embed it below:

In [ ]:
from IPython.display import Image
Image(filename="finalAlignment.png")

**Problem 4 (5 points):** Using the code for the Needleman-Wunsch algorithm from class, create a function that runs the **Smith-Waterman** algorithm instead. You may **not** run Needleman-Wunsch and then zero out the negatives. Instead, modify the code to prevent negative values (e.g., by using max(var,0)). Your function final should produce the matrix of scores only. You **do not** need to do back-tracing. Use the same scoring values as above. 

Change the function name to sw_fun(). Run the sequences from Problem 3 through your function as well and confirm that the positive values are the same.

In [25]:
import numpy as np

# Use these values to calculate scores
match_score = 2
mismatch_score = -1
gap_penalty = -1

# Make a score matrix with these two sequences
seq1 = "ATGAT"
seq2 = "AAGGAT"





def match_fun(a,b):
    if a == b:
        score = 2
    else:
        score = -1
    return score

print("sw_fun")

def sw_fun(seq1,seq2,gap_penalty=-1, match_score=2, mismatch_score=-1):
    m=len(seq1) #length of horizontal sequence
    n=len(seq2) #length of vertical sequence
    score=np.empty(shape=[n+1,m+1]) #array to hold scores
   
    for j in range(0, m + 1): score[0][j] = gap_penalty * j
    
    
    for i in range(0, n + 1): score[i][0] = gap_penalty * i
    
   
    
    for i in range(1, n + 1): 
        for j in range(1, m + 1):
            insert = score[i - 1][j] + gap_penalty 
            delete = score[i][j - 1] + gap_penalty 
            match = score[i - 1][j - 1] + match_fun(seq1[j-1], seq2[i-1])
            
            score[i][j] = max(match, delete, insert)
    
    for i in range(0,m+2):
        for j in range(0,n):
            if score[i][j] <0:
                score[i][j] =0
    return score

sw_fun(seq1,seq2,gap_penalty,match_score,mismatch_score)






def nw_function(seq1,seq2,gap_penalty= -1, match_score= 1, mismatch_score= -1):
    m=len(seq1) #length of horizontal sequence
    n=len(seq2) #length of vertical sequence
    score=np.empty(shape=[n+1,m+1]) #array to hold scores
   
    for j in range(0, m + 1): score[0][j] = gap_penalty * j
    for i in range(0, n + 1): score[i][0] = gap_penalty * i
    
    for i in range(1, n + 1): 
        for j in range(1, m + 1):
            insert = score[i - 1][j] + gap_penalty 
            delete = score[i][j - 1] + gap_penalty 
            match = score[i - 1][j - 1] + match_fun(seq1[j-1], seq2[i-1])
            score[i][j] = max(match, delete, insert)
    
    return score
print("nw_function")
nw_function(seq1,seq2,gap_penalty,match_score,mismatch_score)


print()
print("Sq from Problem 3:")
seq3 = "CCAGT"
seq4 = "ACAAGT"

print("nw_function")
nw_function(seq3,seq4,gap_penalty,match_score,mismatch_score)
print()
print("sw_fun")
sw_fun(seq3,seq4,gap_penalty,match_score,mismatch_score)


sw_fun


array([[0., 0., 0., 0., 0., 0.],
       [0., 2., 1., 0., 0., 0.],
       [0., 1., 1., 0., 2., 1.],
       [0., 0., 0., 3., 2., 1.],
       [0., 0., 0., 2., 2., 1.],
       [0., 0., 0., 1., 4., 3.],
       [0., 0., 0., 0., 3., 6.]])

nw_function


array([[ 0., -1., -2., -3., -4., -5.],
       [-1.,  2.,  1.,  0., -1., -2.],
       [-2.,  1.,  1.,  0.,  2.,  1.],
       [-3.,  0.,  0.,  3.,  2.,  1.],
       [-4., -1., -1.,  2.,  2.,  1.],
       [-5., -2., -2.,  1.,  4.,  3.],
       [-6., -3.,  0.,  0.,  3.,  6.]])


Sq from Problem 3:
nw_function


array([[ 0., -1., -2., -3., -4., -5.],
       [-1., -1., -2.,  0., -1., -2.],
       [-2.,  1.,  1.,  0., -1., -2.],
       [-3.,  0.,  0.,  3.,  2.,  1.],
       [-4., -1., -1.,  2.,  2.,  1.],
       [-5., -2., -2.,  1.,  4.,  3.],
       [-6., -3., -3.,  0.,  3.,  6.]])


sw_fun


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 3., 2., 1.],
       [0., 0., 0., 2., 2., 1.],
       [0., 0., 0., 1., 4., 3.],
       [0., 0., 0., 0., 3., 6.]])